#!/bin/bash -e
LIBPATH=/usr/libexec
source $LIBPATH/mitac-common-functions

PLATFORM_COMPACT_NAME="com.mitac.Hardware.Chassis.Model.S8261"
MB_LIB_PATH="$LIBPATH/plat-svc/$PLATFORM_COMPACT_NAME"
source $MB_LIB_PATH/mainboard_env.sh
ASSERT_FUNCTION_EXIST get_mac_addr_from_fru

KERNEL_DTS_FN=aspeed-bmc-mitac-s8261
FDFFILE="conf-$KERNEL_DTS_FN.dtb"

DO_REBOOT=0

init-uboot() {
    echo "mainboard-init-functions: init-uboot ($VER)"
    source $MB_LIB_PATH/mainboard_env.sh
    BOOTCMD="mw.l 0x1e6e251c 00001f00; run bootspi"
    refresh-uboot-arg bootcmd "$BOOTCMD"
    refresh-uboot-arg fdtfile "$FDFFILE"

    # To make booting with selected DTB configuration.
    # To avoid bmc hung at u-boot due to incorrect config from upgrade and downgrade of firmware, default option is mandatory.
    BOOTSPI="fdt addr 20100000 && fdt header get fitsize totalsize && cp.b 20100000 \${loadaddr} \${fitsize} && bootm \${loadaddr}#\${fdtfile}; echo Booting with default DTB; bootm; echo Error loading kernel FIT image"
    refresh-uboot-arg bootspi "$BOOTSPI"

    echo "Update MAC Address if necessary."
    set +e
    update_mac 0 eth1addr
    update_mac 1 eth2addr
    set -e

    if [ "$DO_REBOOT" == 1 ]; then
        log_oem_redfish_event \
            "Reboot to make new u-boot args working." \
            6 3 \
            "OpenBMC.0.1.MiOBMC" \
            "" ""
        fw_setenv profile "$PROFILE_ID"
        reboot
    fi
}

init-kernel() {
    echo "mainboard-init-functions: init-kernel ($VER)"
}

init-i2c0() {
    BUS=i2c-0
    NEW_DEV=/sys/bus/i2c/devices/$BUS/new_device

    echo "M8261 Devices"
    #echo "Init ??"
    #echo "?? 0x48" > $NEW_DEV
    echo "Init U48"
    echo "pca9546 0x70" > $NEW_DEV
    echo "Init U110"
    echo "pca9546 0x71" > $NEW_DEV
    echo "Init U52"
    echo "pca9546 0x76" > $NEW_DEV
}

init-i2c2() {
    BUS=i2c-2
    NEW_DEV=/sys/bus/i2c/devices/$BUS/new_device

    echo "M8261 Devices"
    echo "Init ??"
    echo "pca9546 0x70" > $NEW_DEV
}

init-i2c6() {
    I2CID=6
    BUS=i2c-$I2CID
    NEW_DEV=/sys/bus/i2c/devices/$BUS/new_device

    echo "M8261 Devices"
}

init-i2c8() {
    BUS=i2c-8
    NEW_DEV=/sys/bus/i2c/devices/$BUS/new_device

    echo "M8261 Devices"
    echo "Init U95"
    echo "pca9534 0x38" > $NEW_DEV
    echo "Init U94"
    echo "pca9538 0x71" > $NEW_DEV
    echo "Init U1_LDL"
    echo "pca9539 0x74" > $NEW_DEV
    echo "Init U2_LDL"
    echo "pca9539 0x75" > $NEW_DEV
    echo "Init U3_LDL"
    echo "pca9539 0x76" > $NEW_DEV
    echo "Init U4_LDL"
    echo "pca9539 0x77" > $NEW_DEV


    echo "IO Board Devices"
    echo "24c02 0x51" > $NEW_DEV
    echo "tmp75 0x4b" > $NEW_DEV

}

init-i2c14() {
    BUS=i2c-14
    NEW_DEV=/sys/bus/i2c/devices/$BUS/new_device

    echo "M8261 Assets"
    echo "Init U40"
    echo "nct7904 0x2e" > $NEW_DEV
}

init-peripheral() {
	echo "mainboard-init-functions: init-peripheral ($VER)"
    # init-i2c0
    #init-i2c2
    #init-i2c6
    #init-i2c8
    #init-i2c14
}

init-service() {
    echo "mainboard-init-functions: init-service ($VER)"
    ln -s $MB_LIB_PATH/mainboard_env.sh /tmp/mainboard_env.sh

    # Create symbolic link according to system.
    # ln -s $LIBPATH/plat-svc/$PLATFORM_COMPACT_NAME/MRD_default.json /tmp/MRD_System.json
    ln -s $LIBPATH/plat-svc/$PLATFORM_COMPACT_NAME/MRD_S8261.json /tmp/MRD_System.json

    source $MB_LIB_PATH/spd_link.sh

    launch_amd_common_service
}
