# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/common/*/recipes-*/*/*.bb \
            ${LAYERDIR}/common/*/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mitac-layer"
BBFILE_PATTERN_mitac-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_mitac-layer = "10"
LAYERSERIES_COMPAT_mitac-layer = "walnascar scarthgap"

BBFILES_DYNAMIC += " \
		meta-arm:${LAYERDIR}/dynamic-layers/arm-layer/recipes-*/*/*.bb \
		meta-arm:${LAYERDIR}/dynamic-layers/arm-layer/recipes-*/*/*.bbappend \
		zephyrcore:${LAYERDIR}/dynamic-layers/zephyrcore-layer/recipes-*/*/*.bb \
		zephyrcore:${LAYERDIR}/dynamic-layers/zephyrcore-layer/recipes-*/*/*.bbappend \
		"

ASPEEDSDKBASE = '${@os.path.normpath("${LAYERDIR}/common/aspeedtech-bmc.meta-aspeed-sdk/")}'
