# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/*/recipes-*/*/*.bb \
            ${LAYERDIR}/*/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mitac-intel-nda-layer"
BBFILE_PATTERN_mitac-intel-nda-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_mitac-intel-nda-layer = "21"
LAYERSERIES_COMPAT_mitac-intel-nda-layer = "walnascar scarthgap"

