# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/*/recipes-*/*/*.bb \
            ${LAYERDIR}/*/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mitac-map-nda-layer"
BBFILE_PATTERN_mitac-map-nda-layer = "^${LAYERDIR}/"
LAYERSERIES_COMPAT_mitac-map-nda-layer = "walnascar scarthgap"

