# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mi-dcscm-layer"
BBFILE_PATTERN_mi-dcscm-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_mi-dcscm-layer = "40"
LAYERSERIES_COMPAT_mi-dcscm-layer = "walnascar scarthgap"
