# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mi-capri-layer"
BBFILE_PATTERN_mi-capri-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_mi-capri-layer = "7"
LAYERSERIES_COMPAT_mi-capri-layer = "walnascar scarthgap"
